CREATE TABLE IF NOT EXISTS urlinfo(
id VARCHAR(40) PRIMARY KEY,
url VARCHAR(1000) NOT NULL,
name VARCHAR(40) NOT NULL,
added_at TIMESTAMP,
updated_at TIMESTAMP,
polling_Interval DECIMAL DEFAULT 5);

CREATE TABLE IF NOT EXISTS urlstatus(
id VARCHAR(40) PRIMARY KEY,
status VARCHAR(20) NOT NULL,
updated_at TIMESTAMP,
FOREIGN KEY (id) REFERENCES urlinfo (id)
);
